version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '6400:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6300:6379'
    volumes:
      - redisDB:/data
volumes:
  progresDB:
  redisDB:
